# Kocicky 1

Using a classifier find the expected _cat_ generated by the system based on input data. 

In [2]:
ftraining = r"C:\P\Machine Learning\kocicky 1\learning.csv"
import numpy as np
training = np.loadtxt(ftraining,delimiter=',')
training.shape

(50000, 4)

Training set contains input parameters (machine set up) in the first 3 column and the last one is resulted cat 1/0

In [3]:
X_training = training[:,:-1]
y_training = training[:,-1]
print(X_training[0:2],y_training[0:2])

[[   2.  110.  467.]
 [   4.  657.  432.]] [ 0.  1.]


Scale the X to mean = 0 using **StandardScaler**, since MLPClassifier below likes prescalled data

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_training)
X_training_scaled = scaler.transform(X_training)
print(X_training_scaled[0:2])

[[-0.69885683 -1.34950503 -0.1037065 ]
 [ 0.70992989  0.54780678 -0.22489099]]


Train the neural network using **MLPClassifier**

In [14]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(12,6), random_state=1,verbose=True)
clf.fit(X_training_scaled, y_training)
print(clf.score(X_training_scaled, y_training))

0.97514


Predict using testing data. Don't forget to scale the input too using StandardScaler

In [11]:
ftraining = r"C:\P\Machine Learning\kocicky 1\test1000.csv"
testing = np.loadtxt(ftraining,delimiter=',')
X_testing = scaler.transform(testing)
y_testing = clf.predict(X_testing)

Output to the text file \n separated

In [12]:
np.savetxt(r"C:\P\Machine Learning\kocicky 1\output.csv",y_testing,delimiter='\n',fmt='%d')

Probabilities of P(y|x)

In [13]:
clf.predict_proba(X_testing)

array([[  1.00000000e+000,   1.64553850e-094],
       [  1.00000000e+000,   3.44057768e-131],
       [  3.67561228e-008,   9.99999963e-001],
       ..., 
       [  1.40578990e-007,   9.99999859e-001],
       [  1.00000000e+000,   1.33376974e-111],
       [  1.00000000e+000,   0.00000000e+000]])