# Text processing with embedding

Get the training data

In [94]:
#filename = r'C:\P\Machine Learning\cotoctes\ucici.csv'
filename = r'C:\P\Machine Learning\cotoctes\ucici_full.csv'
import pandas as pd
#training = pd.read_csv(filename,delimiter='|',header=None,names = ['cat', 'data'])
training = pd.read_csv(filename,delimiter='|',header=None,names = ['cat','other', 'data'])
#training['yr'] = training['other'].str.slice(1, 3)
#training = training[training['yr'].isin(['15','16','17'])]
X_train,X_test = training[0:-10000],training[-10000:]
#X_train,X_test = training[0:-100],training[-100:]

print(X_train.shape,X_test.shape)
for a, b in zip(X_train.data[0:2], X_train.cat[0:2]):
    print("{0:s} => {1:s}".format(a,b))
    
def size_mb(docs):
    return sum(len(s.encode('utf-8')) for s in docs) / 1e6

data_train_size_mb = size_mb(X_train.data)
data_test_size_mb = size_mb(X_test.data)

print("%d items - %0.3fMB (training set)" % (
    len(X_train.data), data_train_size_mb))
print("%d items - %0.3fMB (test set)" % (
    len(X_test.data), data_test_size_mb))

(87951, 3) (10000, 3)
Náklaďáku praskla pneumatika, převrátil se a zasypal silnici pískem => zpr
Nástupkyně Natalie. Novinářka Suková zkusí navázat na tenisovou dynastii => spo
87951 items - 6.076MB (training set)
10000 items - 0.691MB (test set)


In [130]:
max_title_legth = X_train['data'].str.split().str.len().max()
print('Max title legth: {0}'.format(max_title_legth))

Max title legth 39


In [131]:
max_title_char_legth = X_train['data'].str.len().max()
print('Max title legth: {0}'.format(max_title_char_legth))

Max title legth: 255


## Tokenize words

In [97]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences 
from keras.utils import to_categorical

max_title_legth
embedding_vecor_length = 10
vocab_size = 80000

#num_words is tne number of unique words in the sequence, if there's more top count words are taken
tokenizer = Tokenizer(vocab_size)
tokenizer.fit_on_texts(X_train['data'])
sequences = tokenizer.texts_to_sequences(X_train['data'])
sequencesTest = tokenizer.texts_to_sequences(X_test['data'])

word_index = tokenizer.word_index
input_dim = len(word_index) + 1
print('Found %s unique tokens.' % len(word_index))

#max_review_length is the maximum length of the input text so that we can create vector [... 0,0,1,3,50] where 1,3,50 are individual words
data = pad_sequences(sequences, max_title_legth)
dataTest = pad_sequences(sequencesTest, max_title_legth)

print('Shape of data tensor:', data.shape)
print(data)
X_train['sequence'] = data.tolist()

Found 98534 unique tokens.
Shape of data tensor: (87951, 39)
[[    0     0     0 ...,  7886   749 49176]
 [    0     0     0 ...,     2  9005 49177]
 [    0     0     0 ...,     2   160  1236]
 ..., 
 [    0     0     0 ...,  4761 48673  1295]
 [    0     0     0 ...,   647    29  1654]
 [    0     0     0 ...,     4  1900   410]]


C:\Users\v.dekanovsky\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


dataTest[0:2]

## Categorize Labels

## Tokenize chars

In [99]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences 
from keras.utils import to_categorical

max_title_char_legth = X_train['data'].str.len().max()
print(max_title_char_legth)
embedding_vecor_length = 10
vocab_size_char = 150

#num_words is tne number of unique words in the sequence, if there's more top count words are taken
tokenizerChar = Tokenizer(num_words=vocab_size,char_level=True)
tokenizerChar.fit_on_texts(X_train['data'])
sequences = tokenizerChar.texts_to_sequences(X_train['data'])
sequencesTest = tokenizerChar.texts_to_sequences(X_test['data'])

word_index = tokenizerChar.word_index
input_dim = len(word_index) + 1
print('Found %s unique tokens.' % len(word_index))

#max_review_length is the maximum length of the input text so that we can create vector [... 0,0,1,3,50] where 1,3,50 are individual words
datachar = pad_sequences(sequences, max_title_char_legth)
datacharTest = pad_sequences(sequencesTest, max_title_char_legth)

datachar[0:2]

255
Found 144 unique tokens.


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 42, 18, 12,  8,  4, 75, 18, 12, 13,  1, 16,  9,  4, 10, 12,  8,
         4,  1, 16,  5,  2, 13, 17,  4,  7,  6, 12,  4, 27,  1, 16, 26,  2,
        11, 

In [98]:
import keras
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(X_train.cat)
y_train_le = le.transform(X_train.cat)
y_test_le = le.transform(X_test.cat)
y_train = keras.utils.to_categorical(y_train_le,4)
y_test = keras.utils.to_categorical(y_test_le,4)
print(y_train[0:4])
print(y_train.shape)
#list(le.inverse_transform(y_train[0:2]))
print(type(y_train_le))
print(y_train[0:2])

[[ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
(87951, 4)
<class 'numpy.ndarray'>
[[ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]]


## Multi Input model

In [110]:
from keras.models import Model
from keras.layers import Dense, Dropout, Activation,Embedding, Flatten,Conv1D,MaxPooling1D, LSTM, Input, concatenate
from keras.optimizers import SGD

#words
inputsWord = Input(shape=(max_title_legth,))
xWord = Embedding(vocab_size+1, 50)(inputsWord)
x1Word = Conv1D(filters=32, kernel_size=2, activation='relu')(xWord)
x1Word = MaxPooling1D(2)(x1Word)
x2Word = Conv1D(filters=32, kernel_size=3, activation='relu')(xWord)
x2Word = MaxPooling1D(2)(x2Word)
x3Word = Conv1D(filters=32, kernel_size=5, activation='relu')(xWord)
x3Word = MaxPooling1D(2)(x3Word)
xWords = concatenate([x1Word,x2Word,x3Word], axis=1)

#chars
inputsChar = Input(shape=(max_title_char_legth,))
xChar = Embedding(vocab_size_char+1, 10)(inputsChar)
x1Char = Conv1D(filters=32, kernel_size=3, activation='relu')(xChar)
x1Char = MaxPooling1D(2)(x1Char)
x2Char = Conv1D(filters=32, kernel_size=5, activation='relu')(xChar)
x2Char = MaxPooling1D(2)(x2Char)
x3Char = Conv1D(filters=32, kernel_size=7, activation='relu')(xChar)
x3Char = MaxPooling1D(2)(x3Char)
xChar = concatenate([x1Char,x2Char,x3Char], axis=1)

x = concatenate([xChar,xWords], axis=1)

x = Conv1D(filters=64, kernel_size=2, activation='relu')(x)
x = Dropout(0.4)(x)
x = MaxPooling1D(2)(x)
x = Flatten()(x)
#x = Dense(32, activation='relu')(x)
#x = Dropout(0.3)(x)
x = Dense(4, activation='softmax')(x)

model5 = Model(inputs=[inputsWord,inputsChar], outputs=x)
adam = keras.optimizers.Adamax(lr=0.002, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model5.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
print(model5.summary())

#from keras.utils import plot_model
#plot_model(model5, to_file=r'C:\Test Cell\model.png')

#from IPython.display import SVG
#from keras.utils.vis_utils import model_to_dot

#SVG(model_to_dot(model5).create(prog='dot', format='svg'))

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_20 (InputLayer)            (None, 255)           0                                            
____________________________________________________________________________________________________
input_19 (InputLayer)            (None, 39)            0                                            
____________________________________________________________________________________________________
embedding_21 (Embedding)         (None, 255, 10)       1510        input_20[0][0]                   
____________________________________________________________________________________________________
embedding_20 (Embedding)         (None, 39, 50)        4000050     input_19[0][0]                   
___________________________________________________________________________________________

In [111]:
import numpy as np
batch_size = 32
model5.fit(x = [data,datachar], y = np.array(y_train), batch_size = batch_size, epochs = 1, validation_data=([dataTest,datacharTest],y_test))

Train on 87951 samples, validate on 10000 samples
Epoch 1/1
87951/87951 [==============================] - 483s - loss: 0.3403 - acc: 0.8693 - val_loss: 0.2004 - val_acc: 0.9349


model5.layers

In [112]:
real = pd.DataFrame(["Studie z Černobylu tvrdí, že radiace zvířatům neškodí. Ale je to pravda?","Od Facebooku nemůžete čekat žádné soukromí, odmítl žalobu americký soud"], columns=['data'])
realsequencesWord = tokenizer.texts_to_sequences(real['data'])
realsequencesChar = tokenizerChar.texts_to_sequences(real['data'])
realWord = pad_sequences(realsequencesWord, max_title_legth)
realChar = pad_sequences(realsequencesChar, max_title_char_legth)
print(realWord)
print(realChar)
pred = model5.predict(x = [realWord,realChar])
pred

[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0   938     8 14266    37    34 35248 42418 10625    20
      7    16  4380]
 [    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0    25   979  6862  3216  1589  3205   635
   1648   776    55]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  

array([[ 0.78079575,  0.02268641,  0.12399808,  0.07251977],
       [ 0.00708062,  0.0053653 ,  0.55207062,  0.43548355]], dtype=float32)

In [113]:
[le.inverse_transform(t.argmax()) for t in pred]

['ona', 'tec']

In [114]:
filename = r'C:\P\Machine Learning\cotoctes\testovaci.csv'
testing = pd.read_csv(filename,delimiter='|',header=None,names = ['data'])
testingsequencesWord = tokenizer.texts_to_sequences(testing['data'])
testingsequencesChar = tokenizerChar.texts_to_sequences(testing['data'])
testingWord = pad_sequences(testingsequencesWord, max_title_legth)
testingChar = pad_sequences(testingsequencesChar, max_title_char_legth)
tr = model5.predict([testingWord,testingChar])
print(len(tr))
tres = [le.inverse_transform(t.argmax()) for t in tr]
tres[0:4]
testing['res'] = tres
testing

1000


data  res
0    Celtic znemožnil v boji o Ligu mistrů Astanu, ...  spo
1    Katar obnovuje plné diplomatické styky s Íráne...  zpr
2    Před 100 lety se narodil česko-židovský badate...  tec
3    Pioneer má první interní mechaniku pro přehráv...  tec
4    Studie z Černobylu tvrdí, že radiace zvířatům ...  ona
5     Černý pátek je tu. Jak a kde si počíhat na slevy  tec
6    Karolína Plíšková začne hájit trůn. O číslo 1 ...  spo
7    Od Facebooku nemůžete čekat žádné soukromí, od...  tec
8    Oparům se lze bránit. Pomohou antivirotika i p...  ona
9    Vyhovuje nám, že nás předem odepisují, soudí z...  spo
10   Zbavte se rutinních prací s e-maily. Správné p...  tec
11   Motocyklista Abraham bude i nadále jezdit za t...  spo
12   Bez bodu, poslední. Sokolovští fotbalisté se p...  spo
13   Čeští mladíci zdolali domácí Gruzii a jsou v s...  spo
14   Muž najel u Paříže do lidí na zahrádce restaur...  zpr
15   TÝDEN OBRAZEM: konec ramadánu, hlava v tlamě k...  zpr
16   Podvodný e-mail chce jménem exekutora peníze, ...  tec
17        První televizor s Windows 10 míří do prodeje  tec
18   Trump chce vzít peníze vědcům. Univerzity přij...  zpr
19   Jak se „ruská propaganda“ dostala až do projev...  zpr
20   Muž se nepohodl s kolegou kvůli pracovní morál...  zpr
21   Osvoboďte bradavky, hlásá Naomi Campbellová a ...  ona
22   Zeman se setká s Chovancem, chce se ho zeptat ...  zpr
23   Software zdarma: Aktivujte virtuální plochy i ...  tec
24   Ženy mají v kuchyni cit pro detail a systém, ř...  ona
25   Pět triků, díky kterým při chůzi spálíte mnohe...  ona
26   VIDEO: Musel jsem se krotit, říká Nečesaný o s...  zpr
27   Florbalisté Bulldogs Brno poznali svět, chtějí...  spo
28   Za výhru nad Spartou špekáčky od řezníka. Fotb...  spo
29   100 POHLEDŮ: Blahobytná rodinka na nádraží v O...  zpr
..                                                 ...  ...
970  Facebook „znemožnil“ zneužívání dat ke šmírová...  tec
971  Kancelářská sponka v akci: umí udržet culík i ...  ona
972  Microsoft koupil deset milionů molekul synteti...  tec
973  Lidé jej vraceli zlomený, nyní Microsoft s chy...  tec
974  OBRAZEM: Žlutá blond nemusí vypadat lacině, do...  ona
975  Tragická nehoda autobusu v Rusku, zemřelo 14 l...  zpr
976  Otestovali jsme (ne)ovladatelné hračky. Minidr...  tec
977  Proč letadlo malovalo letadlo? Piloti testoval...  tec
978  Britští vědci představili jednoduchý kapesní „...  tec
979  Před 100 lety si britští králové začali říkat ...  tec
980  Nechci to vidět! Po hrůze z Wimbledonu přišla ...  spo
981  Záchranná brzda pro PC aneb co pomůže získat z...  tec
982  Google opravuje prohlížeč Chrome. Záplaty dost...  tec
983  Burnett pokračuje. S Pardubicemi se chce popra...  spo
984  Kam se dalo za 180 minut dojet vlakem za císař...  spo
985  Žijeme naruby: chceme sex, ale místo něj se vě...  ona
986  STAN chce pro učitele plat od 37 tisíc či novo...  zpr
987  Apple chce použít drony, aby vylepšil mapy a d...  tec
988  Stát nakoupí potraviny pro lidi v nouzi, nově ...  zpr
989  Češi jsou v žebříčku FIFA na 40. místě, do čel...  spo
990  Jsme stříbrní, utěšují se američtí fotbalisté ...  spo
991  Závislost na plastikách mi zničila sexuální ži...  ona
992  Internet, jak jej známe, může skončit, varoval...  tec
993  V případě řízení s firmou FAU mohla být poruše...  zpr
994  Pokrok v IT je obrovský, ale skrytý, řekl šéf ...  tec
995  Cítím se jako junior, těší Federera. A vyhlíží...  spo
996  Google ukončí vývoj oblíbeného editoru Picasa,...  tec
997  Spotify hlásí 100 milionů uživatelů měsíčně. A...  tec
998  Software zdarma: Windows vždy ve skvělém stavu...  tec
999  Vyzkoušela jsem mraky diet, říká zpěvačka Ilon...  ona

[1000 rows x 2 columns]

In [115]:
import csv
with open(r'C:\P\Machine Learning\cotoctes\outputkeras2.csv','w') as f:
    wr = csv.writer(f, delimiter='\n')
    wr.writerow(tres)

In [117]:
model5.save(r'C:\P\Machine Learning\cotoctes\904')